[build]
  command = "npm run build"
  functions = "built-functions"
  publish = "dist"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
  force = true

[functions]
  external_node_modules = ["@apollo/server"]
  node_bundler = "esbuild"
  directory = "functions"

[build.environment]
  NODE_VERSION = "18" 