[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
  force = true

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20" 