[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

[functions]
  node_bundler = "esbuild" 