[build]
  command = "npm run build"
  functions = "built-functions"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
  force = true

[functions]
  directory = "built-functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18" 