[build]
  command = "# skip build"
  publish = "public"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
  force = true

[functions]
  external_node_modules = ["@apollo/server", "mongoose", "apollo-server-lambda", "graphql"]
  node_bundler = "esbuild"
  directory = "functions"

[build.environment]
  NODE_VERSION = "20" 